### ISSUE TITLE
final GPA not updating in GPA calculator

### ISSUE THREAD

**Issue by dzinkiv** [walido2001/EECS2311Group5#3]
The GPA calculator does not update the final GPA after changing the mark received.
Steps taken to detect a bug:
- open the CPA calculator feature from the main menu by pressing "GPA Calculator" button
- enter a credit weight
- select the grade from the "grade" dropdown menu
- click the "calculate" button
- select a different grade from the "grade" dropdown menu (without changing credit weight)
- click the "calculate" button
- notice the final GPA field is not updated (shows previous GPA which is different from the course GPA field)

**Comment by AnokyeY** [comment]
Gpa is calculated based on the courses in the courses added section not what is in the input field. Courses have to be added through input fields and then the user presses Add Courses.

Added instructions for the user to make it more clear
