### ISSUE TITLE
Total Credits field not updating in GPA Calculator

### ISSUE THREAD

**Issue by dzinkiv** [walido2001/EECS2311Group5#4]
The GPA calculator does not update the "Total Credits" field after changing the credit weight of a particular course.

Steps taken to detect a bug:
- open the CPA calculator feature from the main menu by pressing "GPA Calculator" button
- enter a credit weight
- select the grade from the "grade" dropdown menu
- click the "calculate" button
- enter a different credit weight (without changing anything else)
- click the "calculate" button
- notice the "Total Credits" field is not updated; it shows the previous total credits value which is different from the entered credit weight value

**Comment by AnokyeY** [comment]
Gpa is calculated based on the courses in the courses added section, added instructions for the user to make it more clear
