### ISSUE TITLE
"Courses Added" window is not updating properly in GPA Calculator

### ISSUE THREAD

**Issue by dzinkiv** [walido2001/EECS2311Group5#5]
The GPA calculator does not correctly update the "Courses Added" window after modifying the course information.
Steps taken to detect a bug:
- open the CPA calculator feature from the main menu by pressing "GPA Calculator" button
- in the first row enter course name, credit weight, and select grade from "Grade" dropdown menu
- click the "calculate" button
- in the second row enter a different course name, credit weight, and select grade from "Grade" dropdown menu
- click the "calculate" button
- in the second row, modify the course name
- click the "calculate" button
- notice the "Courses Added" window has 3 courses despite entering the info about 2 courses only

**Comment by AnokyeY** [comment]
Gpa is calculated based on the courses in the courses added section not what is in the input field. Courses have to be added through input fields and then the user presses Add Courses.

Added instructions for the user to make it more clear
