### ISSUE TITLE
Total credits and GPA update without modifying course credits and grade info

### ISSUE THREAD

**Issue by dzinkiv** [walido2001/EECS2311Group5#6]
The total GPA field changes total credits and total GPA values after modifying the "course name" information (without modifying the course credit and grade info).

Steps taken to detect a bug:
- open the CPA calculator feature from the main menu by pressing "GPA Calculator" button
- in the first row enter any course name, enter "3" for credit weight, and select grade "A+" from "Grade" dropdown menu
- click the "calculate" button
- in the second row enter a different course name, enter "3" for credit weight, and select grade "D" from "Grade" dropdown menu
- click the "calculate" button
- note the total credits is 6 and total GPA value is 5.5 as it should be
- in the second row, modify the course name without modifying any other information
- click the "calculate" button
- notice the total credits and total GPA values changed to 9 and 4.33 respectively

**Comment by AnokyeY** [comment]
Gpa is calculated based on the courses in the courses added section, added instructions for the user to make it more clear
